# Generated by Django 5.2.7 on 2025-10-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("noe", "Noé"),
                            ("baz", "Baz"),
                            ("philo", "Philo"),
                            ("maya", "Maya"),
                            ("jules", "Jules"),
                            ("clotilde", "Clotilde"),
                            ("pierre", "Pierre"),
                            ("lorene", "Lorene"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
